export const ALL_PRODUCT = 'ALL_PRODUCT'
export const ALL_PRODUCT_SUCCES = 'ALL_PRODUCT_SUCCES'
export const ALL_PRODUCT_FAIL = 'ALL_PRODUCT_FAIL'

export const PRODUCT_DETAIL = 'PRODUCT_DETAIL'
export const PRODUCT_DETAIL_SUCCES = 'PRODUCT_DETAIL_SUCCES'
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';

export const PRODUCT_DELETE = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const FILTER_PRODUCT = 'FILTER_PRODUCT'
